"""Schema definitions for request/response models."""

from agent_sandbox.schemas.jobs import (
    ArtifactListResponse,
    JobStatusResponse,
    JobSubmitRequest,
    JobSubmitResponse,
)
from agent_sandbox.schemas.responses import (
    ClaudeCliCancelResponse,
    ClaudeCliPollResponse,
    ClaudeCliResponse,
    ClaudeCliSubmitResponse,
    ErrorResponse,
    QueryResponse,
    SummarySchema,
)
from agent_sandbox.schemas.sandbox import (
    ClaudeCliRequest,
    MessageHistoryEntry,
    MultiplayerStatusResponse,
    PromptQueueClearResponse,
    PromptQueueListResponse,
    PromptQueueStatusResponse,
    QueryBody,
    QueuedPromptEntry,
    QueuePromptRequest,
    QueuePromptResponse,
    SessionCancellationStatusResponse,
    SessionHistoryResponse,
    SessionMetadata,
    SessionMetadataResponse,
    SessionShareRequest,
    SessionShareResponse,
    SessionStopRequest,
    SessionStopResponse,
    SessionUnshareRequest,
    SessionUnshareResponse,
    SessionUsersResponse,
    WarmRequest,
    WarmResponse,
    WarmStatusResponse,
)

__all__ = [
    "QueryBody",
    "QueryResponse",
    "ErrorResponse",
    "SummarySchema",
    "ClaudeCliRequest",
    "ClaudeCliResponse",
    "ClaudeCliSubmitResponse",
    "ClaudeCliPollResponse",
    "ClaudeCliCancelResponse",
    "JobSubmitRequest",
    "JobSubmitResponse",
    "JobStatusResponse",
    "ArtifactListResponse",
    "WarmRequest",
    "WarmResponse",
    "WarmStatusResponse",
    "SessionStopRequest",
    "SessionStopResponse",
    "SessionCancellationStatusResponse",
    "QueuedPromptEntry",
    "QueuePromptRequest",
    "QueuePromptResponse",
    "PromptQueueListResponse",
    "PromptQueueClearResponse",
    "PromptQueueStatusResponse",
    # Multiplayer session schemas
    "MessageHistoryEntry",
    "SessionMetadata",
    "SessionShareRequest",
    "SessionShareResponse",
    "SessionUnshareRequest",
    "SessionUnshareResponse",
    "SessionMetadataResponse",
    "SessionHistoryResponse",
    "SessionUsersResponse",
    "MultiplayerStatusResponse",
]
