"""Schema definitions for request/response models."""

from agent_sandbox.schemas.jobs import (
    ArtifactListResponse,
    JobStatusResponse,
    JobSubmitRequest,
    JobSubmitResponse,
    WorkspaceCleanupRequest,
    WorkspaceCleanupResponse,
    WorkspaceDeleteResponse,
    WorkspaceMetadata,
    WorkspaceRetentionStatusResponse,
)
from agent_sandbox.schemas.responses import (
    ErrorResponse,
    QueryResponse,
    SummarySchema,
)
from agent_sandbox.schemas.sandbox import (
    MessageHistoryEntry,
    MultiplayerStatusResponse,
    PromptQueueClearResponse,
    PromptQueueListResponse,
    PromptQueueStatusResponse,
    QueryBody,
    QueuedPromptEntry,
    QueuePromptRequest,
    QueuePromptResponse,
    SessionCancellationStatusResponse,
    SessionHistoryResponse,
    SessionMetadata,
    SessionMetadataResponse,
    SessionShareRequest,
    SessionShareResponse,
    SessionStopRequest,
    SessionStopResponse,
    SessionUnshareRequest,
    SessionUnshareResponse,
    SessionUsersResponse,
    WarmRequest,
    WarmResponse,
    WarmStatusResponse,
)
from agent_sandbox.schemas.session_spawn import (
    ChildSessionEntry,
    ChildSessionListResponse,
    ChildSessionResult,
    ChildSessionStatus,
    SpawnSessionRequest,
    SpawnSessionResponse,
)

__all__ = [
    "QueryBody",
    "QueryResponse",
    "ErrorResponse",
    "SummarySchema",
    "JobSubmitRequest",
    "JobSubmitResponse",
    "JobStatusResponse",
    "ArtifactListResponse",
    "WarmRequest",
    "WarmResponse",
    "WarmStatusResponse",
    "SessionStopRequest",
    "SessionStopResponse",
    "SessionCancellationStatusResponse",
    "QueuedPromptEntry",
    "QueuePromptRequest",
    "QueuePromptResponse",
    "PromptQueueListResponse",
    "PromptQueueClearResponse",
    "PromptQueueStatusResponse",
    # Multiplayer session schemas
    "MessageHistoryEntry",
    "SessionMetadata",
    "SessionShareRequest",
    "SessionShareResponse",
    "SessionUnshareRequest",
    "SessionUnshareResponse",
    "SessionMetadataResponse",
    "SessionHistoryResponse",
    "SessionUsersResponse",
    "MultiplayerStatusResponse",
    # Workspace retention schemas
    "WorkspaceMetadata",
    "WorkspaceCleanupRequest",
    "WorkspaceCleanupResponse",
    "WorkspaceRetentionStatusResponse",
    "WorkspaceDeleteResponse",
    # Child session spawning schemas
    "SpawnSessionRequest",
    "SpawnSessionResponse",
    "ChildSessionStatus",
    "ChildSessionResult",
    "ChildSessionEntry",
    "ChildSessionListResponse",
]
